### ISSUE TITLE
1.20.5 spigot (yes, ill be that guy haha)

### ISSUE THREAD

**Issue by mrfloris** [Guarmanda/LootChest#60]
Hey, woops, sorry :P but yep, it doesn't work on the freshly build 1.20.5 spigot jar, which was to be expected.

I thought i'd just give a friendly heads-up and share my quick-test findings. 

```
[21:00:26] [Server thread/WARN]: [LootChest] Task #303 for LootChest v2.4.0 generated an exception
java.lang.NoClassDefFoundError: com/comphenix/protocol/PacketType$Play$Server
    at org.holoeasy.packet.delete.DeletePacketB.delete(DeletePacketB.kt:15) ~[?:?]
    at org.holoeasy.line.Line.<init>(Line.kt:20) ~[?:?]
    at org.holoeasy.line.Line.<init>(Line.kt:13) ~[?:?]
    at org.holoeasy.line.TextLine.<init>(TextLine.kt:19) ~[?:?]
    at fr.black_eyes.lootchest.LootChestHologram.setLine(LootChestHologram.java:167) ~[?:?]
    at fr.black_eyes.lootchest.LootChestHologram.setText(LootChestHologram.java:154) ~[?:?]
    at fr.black_eyes.lootchest.LootChestHologram.setLoc(LootChestHologram.java:86) ~[?:?]
    at fr.black_eyes.lootchest.Utils.reactivateEffects(Utils.java:247) ~[?:?]
    at fr.black_eyes.lootchest.Main$4.lambda$run$0(Main.java:303) ~[?:?]
    at org.bukkit.craftbukkit.v1_20_R4.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.5-R0.1-SNAPSHOT.jar:4097-Spigot-b698b49-48f96fb]
    at org.bukkit.craftbukkit.v1_20_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.5-R0.1-SNAPSHOT.jar:4097-Spigot-b698b49-48f96fb]
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1397) ~[spigot-1.20.5-R0.1-SNAPSHOT.jar:4097-Spigot-b698b49-48f96fb]
    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:402) ~[spigot-1.20.5-R0.1-SNAPSHOT.jar:4097-Spigot-b698b49-48f96fb]
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1293) ~[spigot-1.20.5-R0.1-SNAPSHOT.jar:4097-Spigot-b698b49-48f96fb]
    at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1064) ~[spigot-1.20.5-R0.1-SNAPSHOT.jar:4097-Spigot-b698b49-48f96fb]
    at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:311) ~[spigot-1.20.5-R0.1-SNAPSHOT.jar:4097-Spigot-b698b49-48f96fb]
    at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.PacketType$Play$Server
    at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160) ~[spigot-api-1.20.5-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.20.5-R0.1-SNAPSHOT.jar:?]
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
    ... 17 more
```

If you need any additional info, feel free to let me know. And best of luck with 1.20.5, I see that paper has some fun big change coming too https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/

**Comment by Guarmanda** [comment]
I transmit immediately to hologramlib by making an issue there

**Comment by Guarmanda** [comment]
1.20.6 won't have protocollib requirement anymore, I changed the hologram library again. But I have to solve some reflections issues caused by paper team

**Comment by Guarmanda** [comment]
Problems solved in last push, will update when I will have finished some features
